name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    name: PHP ${{ matrix.php-version }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.2', '8.3']
        experimental: [ false ]
        include:
          - php-version: '8.4'
            experimental: true
    steps:
      - uses: actions/checkout@v4

      - uses: swatinem/rust-cache@v2

      - name: Remove conflicting llvm packages
        run: sudo apt remove libclang1-13 llvm-13 libclang1-15 llvm-15

      - name: Install valgrind
        run: sudo apt-get install -y valgrind

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      - name: Build
        run: cargo build --release --verbose

      - name: Tests
        run: ./run-tests.php -n tests -d extension=./target/release/libphp_json5.so -m -q --show-diff
